INSERT INTO EMPLOYEE(FIRST_NAME,LAST_NAME,EMPLOYEE_CODE)  VALUES('Tam','Nguyen',1755241) 
INSERT INTO EMPLOYEE(FIRST_NAME,LAST_NAME,EMPLOYEE_CODE)  VALUES('Nguyen','Tam',1755242) 
INSERT INTO EMPLOYEE(FIRST_NAME,LAST_NAME,EMPLOYEE_CODE)  VALUES('Tam','Tam Nguyen',1755243) 
INSERT INTO EMPLOYEE(FIRST_NAME,LAST_NAME,EMPLOYEE_CODE)  VALUES('Nguyen',' TamNguyen',1755244) 
