export const GET_EMP_REQUEST = "GET_EMP_REQUEST";
export const GET_EMP_SUCCESS = "GET_EMP_SUCCESS";
export const GET_EMP_FAILED = "GET_EMP_FAILED";

export const DELETE_EMP_BY_ID = "DELETE_EMP_BY_ID";
export const DELETE_EMP_BY_ID_FAILED = "DELETE_EMP_BY_ID_FAILED"
export const DELETE_EMP_BY_ID_SUCCESS = "DELETE_EMP_BY_ID_SUCCESS"
 


