export const GET_EMP_REQUEST = "GET_EMP_REQUEST";
export const GET_EMP_SUCCESS = "EM_REQUEST_SUCCESS";
export const GET_EMP_FAILED = "GET_EMP_FAILED";
export const ADD_EMP_REQUEST = "ADD_EMP_REQUEST"
export const DELETE_EMP_BY_ID = "DELETE_EMP_BY_ID";
export const UPDATE_EMP_REQUEST = 'UPDATE_EMP_REQUEST'
 


